name: verify-installer
description: Verify installer behavior without Intune

inputs:
  app:
    description: Target application name
    required: true

runs:
  using: composite
  steps:
    - name: Install powershell-yaml
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml -Scope CurrentUser -Force

    - name: Verify installer
      shell: pwsh
      run: |
        scripts/verify-installer.ps1 -App "${{ inputs.app }}"
